repos:
  - repo: local
    hooks:
      - id: gitleaks-local
        name: gitleaks-local
        entry: tools/gitleaks/gitleaks.exe protect --staged --redact --verbose --config .gitleaks.toml
        language: system
        pass_filenames: false