services:
  xray:
    image: ghcr.io/xtls/xray-core:26.7.11
    container_name: xray-core
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./xray/output/server-config.json:/etc/xray/config.json:ro
    command: ["run", "-config", "/etc/xray/config.json"]